/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WorkspaceIdRouteImport } from './routes/$workspaceId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as WorkspaceIdConnectionsRouteImport } from './routes/$workspaceId/connections'
import { Route as WorkspaceIdBookmarksRouteImport } from './routes/$workspaceId/bookmarks'
import { Route as WorkspaceIdEnvironmentIdRouteImport } from './routes/$workspaceId/$environmentId'
import { Route as WorkspaceIdEnvironmentIdIndexRouteImport } from './routes/$workspaceId/$environmentId/index'
import { Route as WorkspaceIdSettingsMembersRouteImport } from './routes/$workspaceId/settings/members'
import { Route as WorkspaceIdSettingsEnvironmentsRouteImport } from './routes/$workspaceId/settings/environments'
import { Route as WorkspaceIdSettingsAlertsRouteImport } from './routes/$workspaceId/settings/alerts'
import { Route as WorkspaceIdEnvironmentIdQueuesQueueNameRouteImport } from './routes/$workspaceId/$environmentId/queues/$queueName'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdRoute = WorkspaceIdRouteImport.update({
  id: '/$workspaceId',
  path: '/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIdConnectionsRoute = WorkspaceIdConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const WorkspaceIdBookmarksRoute = WorkspaceIdBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => WorkspaceIdRoute,
} as any)
const WorkspaceIdEnvironmentIdRoute =
  WorkspaceIdEnvironmentIdRouteImport.update({
    id: '/$environmentId',
    path: '/$environmentId',
    getParentRoute: () => WorkspaceIdRoute,
  } as any)
const WorkspaceIdEnvironmentIdIndexRoute =
  WorkspaceIdEnvironmentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceIdEnvironmentIdRoute,
  } as any)
const WorkspaceIdSettingsMembersRoute =
  WorkspaceIdSettingsMembersRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => WorkspaceIdRoute,
  } as any)
const WorkspaceIdSettingsEnvironmentsRoute =
  WorkspaceIdSettingsEnvironmentsRouteImport.update({
    id: '/settings/environments',
    path: '/settings/environments',
    getParentRoute: () => WorkspaceIdRoute,
  } as any)
const WorkspaceIdSettingsAlertsRoute =
  WorkspaceIdSettingsAlertsRouteImport.update({
    id: '/settings/alerts',
    path: '/settings/alerts',
    getParentRoute: () => WorkspaceIdRoute,
  } as any)
const WorkspaceIdEnvironmentIdQueuesQueueNameRoute =
  WorkspaceIdEnvironmentIdQueuesQueueNameRouteImport.update({
    id: '/queues/$queueName',
    path: '/queues/$queueName',
    getParentRoute: () => WorkspaceIdEnvironmentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$workspaceId': typeof WorkspaceIdRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$workspaceId/$environmentId': typeof WorkspaceIdEnvironmentIdRouteWithChildren
  '/$workspaceId/bookmarks': typeof WorkspaceIdBookmarksRoute
  '/$workspaceId/connections': typeof WorkspaceIdConnectionsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/$workspaceId/settings/alerts': typeof WorkspaceIdSettingsAlertsRoute
  '/$workspaceId/settings/environments': typeof WorkspaceIdSettingsEnvironmentsRoute
  '/$workspaceId/settings/members': typeof WorkspaceIdSettingsMembersRoute
  '/$workspaceId/$environmentId/': typeof WorkspaceIdEnvironmentIdIndexRoute
  '/$workspaceId/$environmentId/queues/$queueName': typeof WorkspaceIdEnvironmentIdQueuesQueueNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$workspaceId': typeof WorkspaceIdRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$workspaceId/bookmarks': typeof WorkspaceIdBookmarksRoute
  '/$workspaceId/connections': typeof WorkspaceIdConnectionsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/$workspaceId/settings/alerts': typeof WorkspaceIdSettingsAlertsRoute
  '/$workspaceId/settings/environments': typeof WorkspaceIdSettingsEnvironmentsRoute
  '/$workspaceId/settings/members': typeof WorkspaceIdSettingsMembersRoute
  '/$workspaceId/$environmentId': typeof WorkspaceIdEnvironmentIdIndexRoute
  '/$workspaceId/$environmentId/queues/$queueName': typeof WorkspaceIdEnvironmentIdQueuesQueueNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$workspaceId': typeof WorkspaceIdRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$workspaceId/$environmentId': typeof WorkspaceIdEnvironmentIdRouteWithChildren
  '/$workspaceId/bookmarks': typeof WorkspaceIdBookmarksRoute
  '/$workspaceId/connections': typeof WorkspaceIdConnectionsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/$workspaceId/settings/alerts': typeof WorkspaceIdSettingsAlertsRoute
  '/$workspaceId/settings/environments': typeof WorkspaceIdSettingsEnvironmentsRoute
  '/$workspaceId/settings/members': typeof WorkspaceIdSettingsMembersRoute
  '/$workspaceId/$environmentId/': typeof WorkspaceIdEnvironmentIdIndexRoute
  '/$workspaceId/$environmentId/queues/$queueName': typeof WorkspaceIdEnvironmentIdQueuesQueueNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$workspaceId'
    | '/login'
    | '/signup'
    | '/$workspaceId/$environmentId'
    | '/$workspaceId/bookmarks'
    | '/$workspaceId/connections'
    | '/invite/$token'
    | '/$workspaceId/settings/alerts'
    | '/$workspaceId/settings/environments'
    | '/$workspaceId/settings/members'
    | '/$workspaceId/$environmentId/'
    | '/$workspaceId/$environmentId/queues/$queueName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$workspaceId'
    | '/login'
    | '/signup'
    | '/$workspaceId/bookmarks'
    | '/$workspaceId/connections'
    | '/invite/$token'
    | '/$workspaceId/settings/alerts'
    | '/$workspaceId/settings/environments'
    | '/$workspaceId/settings/members'
    | '/$workspaceId/$environmentId'
    | '/$workspaceId/$environmentId/queues/$queueName'
  id:
    | '__root__'
    | '/'
    | '/$workspaceId'
    | '/login'
    | '/signup'
    | '/$workspaceId/$environmentId'
    | '/$workspaceId/bookmarks'
    | '/$workspaceId/connections'
    | '/invite/$token'
    | '/$workspaceId/settings/alerts'
    | '/$workspaceId/settings/environments'
    | '/$workspaceId/settings/members'
    | '/$workspaceId/$environmentId/'
    | '/$workspaceId/$environmentId/queues/$queueName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceIdRoute: typeof WorkspaceIdRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceId': {
      id: '/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/$workspaceId'
      preLoaderRoute: typeof WorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceId/connections': {
      id: '/$workspaceId/connections'
      path: '/connections'
      fullPath: '/$workspaceId/connections'
      preLoaderRoute: typeof WorkspaceIdConnectionsRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/$workspaceId/bookmarks': {
      id: '/$workspaceId/bookmarks'
      path: '/bookmarks'
      fullPath: '/$workspaceId/bookmarks'
      preLoaderRoute: typeof WorkspaceIdBookmarksRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/$workspaceId/$environmentId': {
      id: '/$workspaceId/$environmentId'
      path: '/$environmentId'
      fullPath: '/$workspaceId/$environmentId'
      preLoaderRoute: typeof WorkspaceIdEnvironmentIdRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/$workspaceId/$environmentId/': {
      id: '/$workspaceId/$environmentId/'
      path: '/'
      fullPath: '/$workspaceId/$environmentId/'
      preLoaderRoute: typeof WorkspaceIdEnvironmentIdIndexRouteImport
      parentRoute: typeof WorkspaceIdEnvironmentIdRoute
    }
    '/$workspaceId/settings/members': {
      id: '/$workspaceId/settings/members'
      path: '/settings/members'
      fullPath: '/$workspaceId/settings/members'
      preLoaderRoute: typeof WorkspaceIdSettingsMembersRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/$workspaceId/settings/environments': {
      id: '/$workspaceId/settings/environments'
      path: '/settings/environments'
      fullPath: '/$workspaceId/settings/environments'
      preLoaderRoute: typeof WorkspaceIdSettingsEnvironmentsRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/$workspaceId/settings/alerts': {
      id: '/$workspaceId/settings/alerts'
      path: '/settings/alerts'
      fullPath: '/$workspaceId/settings/alerts'
      preLoaderRoute: typeof WorkspaceIdSettingsAlertsRouteImport
      parentRoute: typeof WorkspaceIdRoute
    }
    '/$workspaceId/$environmentId/queues/$queueName': {
      id: '/$workspaceId/$environmentId/queues/$queueName'
      path: '/queues/$queueName'
      fullPath: '/$workspaceId/$environmentId/queues/$queueName'
      preLoaderRoute: typeof WorkspaceIdEnvironmentIdQueuesQueueNameRouteImport
      parentRoute: typeof WorkspaceIdEnvironmentIdRoute
    }
  }
}

interface WorkspaceIdEnvironmentIdRouteChildren {
  WorkspaceIdEnvironmentIdIndexRoute: typeof WorkspaceIdEnvironmentIdIndexRoute
  WorkspaceIdEnvironmentIdQueuesQueueNameRoute: typeof WorkspaceIdEnvironmentIdQueuesQueueNameRoute
}

const WorkspaceIdEnvironmentIdRouteChildren: WorkspaceIdEnvironmentIdRouteChildren =
  {
    WorkspaceIdEnvironmentIdIndexRoute: WorkspaceIdEnvironmentIdIndexRoute,
    WorkspaceIdEnvironmentIdQueuesQueueNameRoute:
      WorkspaceIdEnvironmentIdQueuesQueueNameRoute,
  }

const WorkspaceIdEnvironmentIdRouteWithChildren =
  WorkspaceIdEnvironmentIdRoute._addFileChildren(
    WorkspaceIdEnvironmentIdRouteChildren,
  )

interface WorkspaceIdRouteChildren {
  WorkspaceIdEnvironmentIdRoute: typeof WorkspaceIdEnvironmentIdRouteWithChildren
  WorkspaceIdBookmarksRoute: typeof WorkspaceIdBookmarksRoute
  WorkspaceIdConnectionsRoute: typeof WorkspaceIdConnectionsRoute
  WorkspaceIdSettingsAlertsRoute: typeof WorkspaceIdSettingsAlertsRoute
  WorkspaceIdSettingsEnvironmentsRoute: typeof WorkspaceIdSettingsEnvironmentsRoute
  WorkspaceIdSettingsMembersRoute: typeof WorkspaceIdSettingsMembersRoute
}

const WorkspaceIdRouteChildren: WorkspaceIdRouteChildren = {
  WorkspaceIdEnvironmentIdRoute: WorkspaceIdEnvironmentIdRouteWithChildren,
  WorkspaceIdBookmarksRoute: WorkspaceIdBookmarksRoute,
  WorkspaceIdConnectionsRoute: WorkspaceIdConnectionsRoute,
  WorkspaceIdSettingsAlertsRoute: WorkspaceIdSettingsAlertsRoute,
  WorkspaceIdSettingsEnvironmentsRoute: WorkspaceIdSettingsEnvironmentsRoute,
  WorkspaceIdSettingsMembersRoute: WorkspaceIdSettingsMembersRoute,
}

const WorkspaceIdRouteWithChildren = WorkspaceIdRoute._addFileChildren(
  WorkspaceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceIdRoute: WorkspaceIdRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
